using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Events2Code.Logic
{
    public static class JsCodeGenerator
    {
        public static string Generate(IList<EventHandlerInfo> handlers, string bootstrapFunction, string entityLogicalName, string formName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by Events2Code (XrmToolBox) on " + DateTime.Now.ToString("yyyy-MM-dd"));
            sb.AppendLine("// Entity: " + entityLogicalName + "   Form: " + formName);
            sb.AppendLine("// Register ONLY this function on the form OnLoad event (pass execution context).");
            sb.AppendLine("\"use strict\";");
            sb.AppendLine();

            AppendNamespaceDeclarations(sb, bootstrapFunction);

            sb.AppendLine(bootstrapFunction + " = function (executionContext) {");
            sb.AppendLine("    var formContext = executionContext.getFormContext();");

            var convertible = handlers.Where(h => h.IsConvertible).ToList();

            AppendSection(sb, "Form OnSave", convertible.Where(h => h.Kind == EventKind.FormOnSave),
                h => "formContext.data.entity.addOnSave(" + HandlerExpression(h) + ");");

            AppendSection(sb, "Attribute OnChange", convertible.Where(h => h.Kind == EventKind.AttributeOnChange),
                h => "formContext.getAttribute(\"" + h.TargetName + "\").addOnChange(" + HandlerExpression(h) + ");");

            var tabs = convertible.Where(h => h.Kind == EventKind.TabStateChange).ToList();
            if (tabs.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("    // --- Tab state change ---");
                foreach (var h in tabs)
                {
                    var local = "tab_" + Sanitize(h.TargetName);
                    sb.AppendLine(Statement(h,
                        "var " + local + " = formContext.ui.tabs.get(\"" + h.TargetName + "\");\n" +
                        "    if (" + local + ") { " + local + ".addTabStateChange(" + HandlerExpression(h) + "); }"));
                }
            }

            var grids = convertible.Where(h => h.Kind == EventKind.GridOnLoad).ToList();
            if (grids.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("    // --- Subgrid OnLoad (grid controls may not exist yet at form OnLoad) ---");
                foreach (var h in grids)
                {
                    var local = "grid_" + Sanitize(h.TargetName);
                    sb.AppendLine(Statement(h,
                        "var " + local + " = formContext.getControl(\"" + h.TargetName + "\");\n" +
                        "    if (" + local + ") { " + local + ".addOnLoad(" + HandlerExpression(h) + "); }"));
                }
            }

            AppendSection(sb, "Original form OnLoad handlers", convertible.Where(h => h.Kind == EventKind.FormOnLoad),
                h => h.FunctionName + "(" + CallArguments(h) + ");");

            sb.AppendLine("};");

            var skipped = handlers.Where(h => !h.IsConvertible).ToList();
            if (skipped.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("// NOT converted (no programmatic registration API) - left registered on the form:");
                foreach (var h in skipped)
                    sb.AppendLine("//   " + h.EventName + " " + h.TargetName + " -> " + h.FunctionName + " (" + h.LibraryName + ")");
            }

            return sb.ToString();
        }

        private static void AppendNamespaceDeclarations(StringBuilder sb, string bootstrapFunction)
        {
            var parts = bootstrapFunction.Split('.');
            for (var i = 1; i < parts.Length; i++)
            {
                var path = string.Join(".", parts.Take(i));
                sb.AppendLine(i == 1
                    ? "var " + path + " = " + path + " || {};"
                    : path + " = " + path + " || {};");
            }
            if (parts.Length > 1) sb.AppendLine();
        }

        private static void AppendSection(StringBuilder sb, string title, IEnumerable<EventHandlerInfo> handlers, Func<EventHandlerInfo, string> render)
        {
            var list = handlers.ToList();
            if (list.Count == 0) return;
            sb.AppendLine();
            sb.AppendLine("    // --- " + title + " ---");
            foreach (var h in list)
                sb.AppendLine(Statement(h, render(h)));
        }

        private static string Statement(EventHandlerInfo h, string code)
        {
            return h.Enabled
                ? "    " + code
                : "    // (disabled in designer) " + code.Replace("\n", "\n    // ");
        }

        // UI registrations pass execution context first (when checked), then the comma-separated parameters.
        private static string HandlerExpression(EventHandlerInfo h)
        {
            var hasParams = !string.IsNullOrWhiteSpace(h.Parameters);
            if (!hasParams && h.PassExecutionContext) return h.FunctionName;
            return "function (executionContext) { " + h.FunctionName + "(" + CallArguments(h) + "); }";
        }

        private static string CallArguments(EventHandlerInfo h)
        {
            var args = new List<string>();
            if (h.PassExecutionContext) args.Add("executionContext");
            if (!string.IsNullOrWhiteSpace(h.Parameters)) args.Add(h.Parameters.Trim());
            return string.Join(", ", args);
        }

        private static string Sanitize(string name)
        {
            return Regex.Replace(name ?? "", "[^A-Za-z0-9_]", "_");
        }
    }
}
